### ISSUE TITLE
MetaMask Overcharging Parameter Proposal

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#103]
When I create a parameter proposal for any parameter value, MetaMask prompts me to pay 10000000000 ADT, when the gMinDeposit is 100 ADT. Also, notice how if I added a decimal point after 9 zeroes in 10000000000 ADT, I get 10.000000000 (10) ADT, not 100.000000000 (100) ADT.

Link to screen recording: https://drive.google.com/open?id=12z8Njd_Vo5r9v1j7BPfhahT9CyjfImMv

---

**UPDATE**: although MetaMask prompts this amount of ADT, the parameter proposal actually goes through. Seems like something in the Rinkeby Testnet was clogging the previous parameter proposals.

**Comment by mnoster** [comment]
I would consider opening an issue with MetaMask about this one
