### ISSUE TITLE
Change all "Stage Ends" to "Time Remaining"

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#107]
Using the Aragon Library as a reference, please change all "Stage Ends" timers with the Aragon-style "Time Remaining" format. An example of the Aragon format is: 

![image](https://user-images.githubusercontent.com/21111803/37123897-cb131fea-221a-11e8-8fbc-5d03628ae462.png)

If possible, please pause all countdown timers on the UI side, while updating it's snapshot upon every refresh of the page. 

[Aragon UI](https://github.com/aragon/aragon-ui)
[InVision to reference](https://invis.io/JCG1VBU4EB9#/281607434_In_Registry)

**Comment by samkim28** [comment]
can use this: https://ui.aragon.one/countdown/
