### ISSUE TITLE
Governance Module Warnings

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#108]
Create warnings for users who attempt to propose a crazy value for a parameter. 

![image](https://user-images.githubusercontent.com/21111803/39089708-2a177c5e-4582-11e8-98b3-1dd3526ff5bf.png)

![image](https://user-images.githubusercontent.com/21111803/39089709-2f52daba-4582-11e8-803c-b9fe079c8df9.png)

**Comment by mnoster** [comment]
Lets have a meeting about the values we consider dangerous.
