### ISSUE TITLE
Adding the rescueTokens Function

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#109]
Please add the rescue tokens function in the `Hidden Voting Tokens` section. A screenshot is found below:

![image](https://user-images.githubusercontent.com/21111803/37422858-7be1e76c-2779-11e8-8205-1038bab09ec9.png)

**Current Approved ADT**
- The current version of `Total Current Voting Rights`

**Expired Voting ADT**
- The new `rescueTokens` function

**Unlocked Voting ADT**
- The current version of `Available Unlocked Voting Rights`
- Make sure to have `Unlocked Voting Tokens` be `Unlocked Voting ADT`

[Wireframe Here](https://projects.invisionapp.com/d/main#/console/13044112/272872561/preview)

***

When users commit votes, but don't reveal them, they need to call the `rescueTokens` function in order to withdraw them. This is from Mike's "TCR Owner's Manual":

![image](https://user-images.githubusercontent.com/21111803/37245150-cb2c2b0e-2448-11e8-8e96-f970f321a9d0.png)

I know we don't explicitly display this ability in the UI, but is the ability implemented in our DApp?

# Test
### SETUP
- Wallet 1 = W1
- Wallet 2 = W2
- Wallet 3 = W3
- Wallet 4 = W4

### PROCEDURE
1. W1 applies `apple.com` with 2,000 ADT staked
2. W2 challenges `apple.com` with 2,000 ADT staked
3. W3 commits 50 ADT to `SUPPORT`
4. W4 commits 49 ADT to `OPPOSE`
5. W3 reveals 50 ADT to `SUPPORT`
6. Voting concludes, `apple.com` is admitted into the registry:
   - W1 has `apple.com` in the registry, with the original stake (2,000 ADT) and the special dispensation (1,000 ADT) all within the listing, available to be withdrawn by the applicant at any time
   - W2 loses the 2,000 ADT staked in challenge, 1,000 to W1 and 1,000 to W3
   - W3 calls the `claimVotingRewards` function and receives 1,000 ADT, while also calling `withdrawVotingRights` to receive the 50 ADT used in voting
   - W4 has 49 voting rights displayed, but has the inability to call `withdrawVotingRights` because W4 never revealed the 49 committed votes. Therefore, we need to display the ability to call `rescueTokens` so that the voters who commit but do not reveal have the ability to withdraw their tokens from the PLCR contract. 

_Please Note: It is confirmed that W4 is unable to withdraw voting rights because they were not revealed. Therefore, an ability to `rescueTokens` is needed._

**Comment by mnoster** [comment]
In Progress

The Challenges API Endpoint is being refactored to return the pollId needed for the rescue function

**Comment by eduardo-munoz** [comment]
@mnoster updated with the design
