### ISSUE TITLE
Remove and replace 'pify' module

### ISSUE THREAD

**Issue by mnoster** [AdChain/AdChainRegistryDapp#124]
The `pify` module breaks the build due to uglifyJS. 

Need to implement alternative. 

Cannot modify the `react-scripts` package safely.

The build should work after this, in hopes of hosting on S3 instead of ELB.

**Comment by eduardo-munoz** [comment]
@mnoster what's the status on this issue? Can it be closed?

**Comment by mnoster** [comment]
Yea already did this.
 **Notes:**  `pify` is a dependency of one of the `node_modules`. Since babel does not transpile the ES6 dependencies, manual transpilation is needed for some dependencies. Also replace the `bluebird` pify with `new Promise.all`
