### ISSUE TITLE
HELP Dropdown in Navigation Column

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#139]
Let's clean-up and add functionality to the HELP dropdown in the navigation column:

- [x] Clicking the `VIEW GUIDES` section prompts the `HOW DOES THIS THING WORK` guide modal
- [x] Remove the `SHOW ALL TOOLTIPS` section as we will no longer be showing this
- [x] Clicking the `HELP CENTER` section sends the user [here](https://adchain.zendesk.com/hc/en-us/categories/115000415353-adChain-Registry-DApp)
- [x] Clicking the `SUBMIT A FEATURE REQUEST` section sends the user [here](https://adchain.zendesk.com/hc/en-us/requests/new)

- [x] Add `WELCOME GUIDE` to the top of the Help dropdown list. This will re-populate the welcome guide in case they previously chose to never see it again. @samkim28

**Comment by samkim28** [comment]
Since we're going to have a Welcome Guide and a View Guides in the help menu, should we rename View Guides to something else? or rename welcome guide? Might be confusing to have both named that way.

**Comment by eduardo-munoz** [comment]
@samkim28 Help Dropdown:
- WELCOME
- VIEW GUIDES
- HELP CENTER
- SUBMIT A FEATURE REQUEST
