### ISSUE TITLE
iframe Reddit just like Rocket.Chat

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#141]
We're thinking about utilizing reddit to have a bot create a post when a domain is applied into the adChain Registry. The first step is putting the [adChain Subreddit](https://www.reddit.com/r/adChain/) in an iframe similar to how we have Rocket.Chat.

**Comment by samkim28** [comment]
Maybe we can do a combination of the Reddit Widget (https://www.reddit.com/widget) and the Reddit API to create new posts?
