### ISSUE TITLE
Challenge - Fourth Step

### ISSUE THREAD

**Issue by Ethereum1227** [AdChain/AdChainRegistryDapp#152]
![Screen Shot 2018-03-23 at 10.21.07 AM.png](https://images.zenhubusercontent.com/5ab3fdb64b5806bc2bcc01ea/2bea3b9e-0cbb-42cf-8cbf-2008abae250f)

We could remove this step entirely. Since we are telling them on the first step only domains In Application or In Registry can be challenged and this step doesn't really give the user much. Thoughts?

**Comment by eduardo-munoz** [comment]
Got it @Ethereum1227
