### ISSUE TITLE
"How do I challenge a domain?" section in "How does this thing work?"  - The Last Step

### ISSUE THREAD

**Issue by Ethereum1227** [AdChain/AdChainRegistryDapp#153]
Thinking the Last Step of the walkthrough for challenging a domain should be. 
![Screen Shot 2018-03-23 at 10.31.20 AM.png](https://images.zenhubusercontent.com/5ab3fdb64b5806bc2bcc01ea/86bb7b4b-d132-457c-a4bb-fd7e900ce5b8)

Thoughts?

**Comment by eduardo-munoz** [comment]
Got it, so you want the final step in `How do I Challenge a Domain?` to be the Voting modal, to show the user that their challenge pushed the domain into voting? @Ethereum1227
