### ISSUE TITLE
Remove Loading Spinner in Governance Module

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#161]
When the `OPEN PROPOSALS` table is empty, there is an infinite loading spinner that isn't loading anything. The user will think that something will be displayed eventually. Let's add a filler text (similar to the dashboard ones) that reads:

Proposed parameter values will be displayed here. You will have the opportunity to challenge, vote, and reveal from this table.

**Comment by mnoster** [comment]
Got it. Yea just noticed that too.
