### ISSUE TITLE
Revealing a Vote - Step 2

### ISSUE THREAD

**Issue by Ethereum1227** [AdChain/AdChainRegistryDapp#167]
Same issue as committing a vote step 2. 

"The filtered domains are in the voting reveal stage"
<img width="1172" alt="screen shot 2018-04-03 at 10 57 58 am" src="https://user-images.githubusercontent.com/35276813/38266668-2068b388-372e-11e8-912d-e09765eb11a2.png">

But the image shows domains in various other stages.

**Comment by eduardo-munoz** [comment]
Same options as in Issue #165
