### ISSUE TITLE
Allow user to withdraw certain amount like approving voting rights

### ISSUE THREAD

**Issue by eccheung4** [AdChain/AdChainRegistryDapp#169]
![image](https://user-images.githubusercontent.com/1091173/38321151-931fa6bc-37eb-11e8-9099-4a049febcd76.png)

Add input field for amount to withdraw and not just withdraw all unlocked

**Comment by eduardo-munoz** [comment]
@eccheung4 looks like you beat me to documenting this. I have it as issue #196
