### ISSUE TITLE
Re-Designing the Commit View

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#172]
# Problem
There is still a lot of confusion in the single-domain commit view page. The confusion is found: 
- In knowing how many voting rights a user already has
- In knowing how many total tokens a user can use to commit votes
   - Total Tokens Available to Vote = Voting Rights + Displayed ADT Balance on top-right
- In knowing whether they are **SUPPORT**ing the Application or the Challenge
- After the commit is done, in viewing a summary of what just happened (maybe)
- Assure the user that voting doesn't put their tokens in danger

# Solution
- [ ] Replacing the numbers with green checkmarks once the user has completed each step. Also, make the commit data blue in the bottom-right box. Lastly, remove the box shadows that the DApp currently has in the commit view. 

![image](https://user-images.githubusercontent.com/21111803/38791408-5620dafa-40fc-11e8-966d-e6b26961ed65.png)

- The MainTopBar will show how many voting rights the user has
- The MainTopBar will show how many total tokens the wallet owns
- We add "the domain" and underline "domain" in step 2 of commit

- [x] Please add `the domain` to the right of `OPPOSE`

![image](https://user-images.githubusercontent.com/21111803/38585040-478b0354-3ccd-11e8-9a1b-8236fdc731c2.png)

**Comment by samkim28** [comment]
need to update main top bar

**Comment by samkim28** [comment]
Since it's hard to distinguish voting rights between contracts, leaving that out for now. In addition to the buttons being disabled unless an input is entered, support/oppose is chosen, etc.. (already implemented), I will add the green styling to make it even clearer to user that each step is completed.
