### ISSUE TITLE
Expired Voting ADT Feature Not Working

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#177]
# Problem
The `Expired Voting ADT` feature in the user dashboard is not working. It is throwing a transaction error. There is also a recurring bug where users are told that they have 160 ADT expired, when that is not true. 

![image](https://user-images.githubusercontent.com/21111803/38448885-26fe9a46-39bd-11e8-9245-a3fc4deda24b.png)

**Comment by mnoster** [comment]
This ticket is blocked until contract updates occur
