### ISSUE TITLE
GovernX Email Notifications

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#182]
# Problem
There are several things that we must do on our end to seamlessly integrate GovernX's email notification feature.
- Add the option to sign-up for email notification in the welcome steps
- Confirmation modal after the user signs-up telling them to check their email to confirm
- Instructing the user that they will receive daily emails summarizing registry interactions
- Landing modal that tells the user that they have successfully confirmed their subscription. This will be the destination after they click `confirm` in the email. It currently sends them to metax.io
- Landing modal that tells the user that they have successfully unsubscribed. This will be the destination after they click `unsubscribe` in the email.
- The tooltip is the same as the filters tooltip
- Alert the user that the email they submitted is not valid, in case it doesn't follow the standard email format
- Clarify with GovernX what domain the registry will live on while on the mainnet

# Solution
- [x] Add a tooltip that reads: `Receive daily updates on new activity in the adChain Registry. Powered by GovernX`
- [x] Add the `SIGN-UP FOR EMAIL NOTIFICATIONS` modal after the `REWARDS` welcome walkthrough. Also, change the green `FINISH` button in `REWARDS` to say `NEXT` in blue. 
- [x] Add the `PLEASE CONFIRM YOUR SUBSCRIPTION` modal after a user signs-up for email notifications
- [x] Add the `SUBSCRIPTION CONFIRMED` modal as the landing page after a user clicks on `CONFIRM` within their email
- [x] Add the `UNSUBSCRIPTION CONFIRMED` modal as the landing page after a user clicks on `UNSUBSCRIBE` within their email

# Design
InVision found [here](https://invis.io/NZGWIXRJMPW)
@samkim28 and @mnoster you've been added to the invision
SVG for the GovernX logo [here](https://drive.google.com/open?id=1iybL0v7TdOKzoCrNLZEKXFozQboAmF5V)

**Comment by mnoster** [comment]
@eduardo-munoz let's have a meeting tomorrow about the stuff we need to do before launch
