### ISSUE TITLE
Re-Design Governance Modals

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#184]
# Problem
When challenging/voting/revealing for a parameter proposal, users are unclear with:
- What parameter they are interacting with
- A confirmation with how much and to which side they committed (can't)
- A confirmation with how much and to which side they revealed

# Solution
You can find the wireframes [here](https://invis.io/GPGTRFHXZDW#/290735953_PARAMETERS_--CLICK_-gMinDeposit-)

The updates can be found below:
### In Application
- [x] Insert the parameter in question on the top-right

### Voting Commit
- [x] Insert the parameter in question on the top-right
- [x] Add `the proposal` to the right of the `SUPPORT or OPPOSE` buttons in step 2
- [x] Force the user to download the commit JSON before submitting vote
- [ ] Alert the user if they've already committed a vote to the parameter proposal

### Voting Reveal
- [x] Insert the parameter in question on the top-right
- [ ] Hide the token amount revealed in the `ADT holders have revealed..`
- [ ] Once the user has revealed their vote, remove the ability to upload JSON and enter reveal data to show a message that summarizes what they did: "You voted to SUPPORT the parameter proposal with 10,000 ADT"

**Comment by samkim28** [comment]
Going to finish functionality of the governance reveal container after qa party
