### ISSUE TITLE
Insert RegistryGuideModals across Different Pages

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#213]
# Problem
The RegistryGuideModals are a great resource, but seem to be underutilized by the QA testers. Therefore, we need to prompt the modals automatically for users once they hit certain sections, while also giving them the ability to check the "I don't want to see this again" checkbox. 

# Solution
Include specific RegistryGuideModals when users view certain pages. Below are all of the RegistryGuideModals and where they should appear:

**/domains**
- [ ] What is the adChain Registry?
- [ ] How do I apply a domain into the adChain Registry?
- [ ] How do I challenge a domain?
- [ ] How do I commit a vote?
- [ ] How do I reveal a vote?
- [ ] What is the domain's journey in the adChain Registry?

**/domains/example.com (when a challenge is prompted)**
- [ ] How do I challenge a domain?

**/domains/example.com (when a vote is prompted)**
- [ ] How do I commit a vote?

**/domains/example.com (when a reveal is prompted)**
- [ ] How do I reveal a vote?

**/governance**
- [ ] Have the exact `How do I interact with the Governance Module?` guide pop-up, with the checkbox option that says: "I don't want to see this again".

InVision link [here](https://invis.io/GBGWEDNN6EX)
@samkim28 you're added to inspect it

**Comment by samkim28** [comment]
Should the "I don't want to see this again" checkbox be used so that it applies to all of these? For example: they check "I don't want to see this again" on Governance, but when they go to /Domains, they wouldn't see the pop up because they already checked it?

**Comment by samkim28** [comment]
@eduardo-munoz I refactored the walkthrough component of the registry, but everything seems to still be working fine after my testing. Can you test this a little bit more on your end and see if you see anything weird with it before closing this issue? Thanks!

**Comment by eduardo-munoz** [comment]
works perfectly now even when the user doesn't exit out of the welcome modal, thank you @samkim28
