### ISSUE TITLE
DApp Loading Screen

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#214]
# Problem
When the registry is loading, a plain-white screen is shown. The loading screen has potential for more. (see [image](https://user-images.githubusercontent.com/21111803/38783514-de2140ce-40b7-11e8-9cc8-2d8923723710.png) here)

# Solution
InVision link [here](https://invis.io/E8GWHKM2VN9#/291373580_Loading_Page)
@mnoster invitation to the invision sent

![image](https://user-images.githubusercontent.com/21111803/38783781-159d230c-40bc-11e8-94a0-714a969d6c52.png)

**Comment by mnoster** [comment]
This looks dope
