### ISSUE TITLE
Tell the User to Wait for Reveal

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#216]
# Problem
When a user commits a vote, they can be confused with what's next.

# Solution
Add the following text to the confirmation modal:
`Now that you've committed the vote, you will need to wait for the reveal stage to reveal your vote. You will need your downloaded JSON file to reveal the vote.`

**Comment by samkim28** [comment]
Do you want this text to be displayed in the Transaction Completed Modal? Or within the stage component somewhere?
