### ISSUE TITLE
Limit Commit Unless Token Amount is Specified

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#230]
# Problem
Users are able to commit a vote without having to specify how much ADT they wish to commit. 

# Solution
Restrict the ability to commit until each of the following are completed:
- [x] ADT amount is specified and greater than 0
- [x] A vote option is selected
- [x] The JSON commit file has been downloaded

**Comment by samkim28** [comment]
Support/Oppose buttons are disabled unless a value greater than 0 is entered. Commit Download is disabled until Support/Oppose is chosen. Vote Submit is disabled until file has been downloaded.
Didn't add any additional design to it yet, but can revisit the design aspect of this!
