### ISSUE TITLE
Researching AdBlocker Workarounds for adChain

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#233]
# Problem
Every time a user has their AdBlocker on, they are unable to see anything adChain/adToken-related.

# Solution
We need to first research how much effort it will take us to go around this block, and then implement the necessary edits. 

- [x] Changing adchain.zendesk.com to metax.zendesk.com

**Comment by mnoster** [comment]
URL encoding 'ad' in the request URLS works for some scenarios.
