### ISSUE TITLE
Help instructions to reset metamask

### ISSUE THREAD

**Issue by eccheung4** [AdChain/AdChainRegistryDapp#238]
When metamask gets into weird state with slow transactions.  Instruct user to disable and re-enable metamask to see if it helps if increasing gas price doesn't help first.

**Comment by eduardo-munoz** [comment]
Yes, we can send them to a troubleshoot zendesk article that lists out best practices for MetaMask

**Comment by Cryptosyvino** [comment]
I have been digging for useful troubleshooting info for metamask for days now. I have been attempting to move my Ethereum out of my metamask for days now only to have my transaction hashes never to be found, I have checked the gas-station multiple times for the recommended gas and gwei. I have even tried doubling the amount of the suggested gas/gwei only to have failed and rejected transactions and lost hashes. Should I just reset my account?

**Comment by eccheung4** [comment]
@Cryptosyvino go to chrome extensions and find metamask, then just enable and disable metamask. hope that helps
