### ISSUE TITLE
Make it more apparent if a domain has never applied

### ISSUE THREAD

**Issue by eccheung4** [AdChain/AdChainRegistryDapp#239]
From rocketchat:

walker.flynn
can you add a proper 404 page? It currently looks like all domains that haven't ever applied have been rejected https://publisher.adchain.com/domains/walker-flynn.cool. It is very misleading. If the contract emits an event when the domain first applies you should be able to use the event log to differentiate between never applied and removed.
Maybe rename Stage to something else besides "None", maybe "Never Applied" or "None" is just fine?

**Comment by eduardo-munoz** [comment]
Correct, let's rename the stage `None` to say `Never Applied` and add filler text in the stage map view that reads `This domain has never been applied`

**Comment by samkim28** [comment]
When a user visits a domain profile for a domain that's never been applied, they should now see 'Stage: Never Applied', while hiding the stage map and reddit box so they aren't confused.
