### ISSUE TITLE
Notify user if Meta Mask tx times out 

### ISSUE THREAD

**Issue by mnoster** [AdChain/AdChainRegistryDapp#242]
Since the Mainnet is super slow, we should notify the user if their tx times out instead of just saying it failed.

**Comment by eduardo-munoz** [comment]
@mnoster 
Based off our ability to read MetaMask's properties, what can we display to the user? I'm wondering if we can show them: 

1) A link of their transaction on etherscan
2) The ability to suggest "Too slow? Edit your GWEI" like MetaMask does

**Comment by mnoster** [comment]
@eduardo-munoz 
Good call, I'll look into those features.

**Comment by samkim28** [comment]
related to issue #276
