### ISSUE TITLE
Detect if user has a token allowance when trying to approve voting rights

### ISSUE THREAD

**Issue by mnoster** [AdChain/AdChainRegistryDapp#243]
In order to minimize txs, detect if the user has already allowed the contract to use tokens. 

This could improve usability and lead to less tx over time.

**Comment by eduardo-munoz** [comment]
I thought we already checked if users had the token approved. The logic is utilized when knowing if the user should be shown a loading page of 1 tx or 2 tx's. Is this correct, @samkim28

**Comment by mnoster** [comment]
@eduardo-munoz Yes that is the case for some txs but not all, specifically Pre-approving in the dashboard.
