### ISSUE TITLE
Display Domain Stages for Users when MetaMask is Not Found

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#245]
# Problem
Consumers of the adChain Registry need to be able to "consume" the domains In Registry without any barriers. Although the filters work, it would be best for users without MetaMask to read the registry for domain's In Registry with the green check next to it. 

![image](https://user-images.githubusercontent.com/21111803/39725749-d6167218-521a-11e8-9f69-ec6d9dd85ff5.png)

# Solution
Properly display, at the minimum, the domain's stage next to it even when the user doesn't have MetaMask.

**Comment by mnoster** [comment]
Just fixed. It will be in staging soon.
