### ISSUE TITLE
Change display of Governance Parameters and Values to make it easier for users

### ISSUE THREAD

**Issue by samkim28** [AdChain/AdChainRegistryDapp#249]
We should finalize a list of new names for the parameters so it's easier for users to understand.
Example: 
- minDeposit -> Minimum Deposit
- applyStageLen -> Application Stage Length 

Also, convert the length values from minutes to days (front end). Instead of 7200 mins, show 5 days?

**Comment by eduardo-munoz** [comment]
Correct, I'll gather the list of labels

**Comment by eduardo-munoz** [comment]
minDeposit: Minimum Deposit
applyStageLen: Application Stage Length
commitStageLen: Commit Stage Length
revealStageLen: Reveal Stage Length
dispensationPct: Dispensation Percentage
voteQuorum: Vote Quorum

gMinDeposit: Gov. Minimum Deposit
gApplyStageLen: Gov. Apply Stage Length
gCommitStageLen: Gov. Commit Stage Length
gRevealStageLen: Gov. Reveal Stage Length
gDispensationPct: Gov. Dispensation Percentage
gVoteQuorum: Gov. Vote Quorum
