### ISSUE TITLE
Disable Popup modals for mobile screens

### ISSUE THREAD

**Issue by mnoster** [AdChain/AdChainRegistryDapp#251]
On the Cipher browser the modals seem to break the page. Look into why this is happening. 

Quick solution is to just detect if screen is mobile size and disable modals.

**Comment by eduardo-munoz** [comment]
Can this still be done? Also, I uploaded the new icons (in svg) for the mobile bottom nav found [here](https://drive.google.com/open?id=1bwTNonqwPjUIxiMDXiNAiBpU8iK4Cg4b)
