### ISSUE TITLE
Mobile Site Enhancements

### ISSUE THREAD

**Issue by mnoster** [AdChain/AdChainRegistryDapp#254]
# Overview
In order to enhance the mobile UX, we will be focusing on creating a separate mobile view. The mobile view will be barebones and only focus on the core usability functions. Therefore, it will allow users to:

- Read all domains and their appropriate stages (with countdown timers)
- Apply domains with the ability to input reasoning
- Challenge domains with the ability to input reasoning
- Commit Votes and email the JSON commit file to the address of their choice
- Read the revealed votes score
- Refresh the status of domains that need it
- Purchase ADT via the AirSwap integration
- Read all of the Parameter Values

# Single-Domain Views
### In Application
- [x] Time Remaining
- [x] ADT Required to Challenge: `minDeposit`
- [ ] Your Payout if Successful:  `minDeposit` * `dispensationPct`
- [ ] Percentage of Votes Needed in Your Favor to Win:  `voteQuorum`
- [x] `CHALLENGE` red button

### Voting Commit
- [x] Time Remaining
- [ ] Enter Number of Votes to Commit: `Input field with comma separator`
- [x] Choose Your Side: `SUPPORT {domain}` `OPPOSE {domain}`
   - Make sure to have the button filled when the user clicks on it
- [ ] Enter an Email Address to Send the Commit JSON File: `Input field only for emails`
   - Help text underneath the email input field: `The JSON file is needed to reveal the commit. This can only be done on the desktop view.`
- [x] `COMMIT VOTE` blue button

### Voting Reveal
- [x] Time Remaining
- [x] Percentage Votes Breakdown Chart
- [x] Total Votes to Support
- [x] Total Votes to Oppose
- [ ] Help text: `If you're looking to reveal your committed vote, you must do so in the desktop view with your JSON commit file.`

### Rejected
- [ ] Percentage Votes Breakdown Chart
- [ ] Total Votes to Support
- [ ] Total Votes to Oppose
- [ ] Help text: `Voting for this domain has concluded. The domain has been rejected from the adChain Registry`

### Withdrawn
- [ ] Percentage Votes Breakdown Chart
- [ ] Total Votes to Support
- [ ] Total Votes to Oppose
- [ ] Help text: `Whoever applied this domain has withdrawn it from the adChain Registry. You can apply it below.`
- [ ] `APPLY {domain}` blue button

### Refresh Needed
- [ ] Help text: `Please click the refresh button below to update the domain's stage`
- [ ] `REFRESH` #424242 black button

### None
- [ ] Help text: `This domain has never been applied to the adChain Registry. Click the button below to apply it.`
- [ ] `APPLY {domain}` blue button

# Bottom-Menu
- DOMAINS
- APPLY
- ADTOKEN
- GOVERNANCE
- [ ] Have them all be #424242, with the inactive ones set to 50% Opacity
- Their SVG icons can be found [here](https://drive.google.com/open?id=1bwTNonqwPjUIxiMDXiNAiBpU8iK4Cg4b)

# InVision Wireframes
Found [here](https://invis.io/ARJ2NS1N7SV#/298197985_DOMAINS)

---

# User Flows
![image](https://user-images.githubusercontent.com/21111803/40323781-56464302-5ceb-11e8-9d93-0530aa64f0ea.png)

**Comment by mnoster** [comment]
@eduardo-munoz Created an issue for this. Go ahead and throw in any specs if needed. I'll just be referencing the Invision designs.

**Comment by eduardo-munoz** [comment]
Solid, I'll breakdown everything.
