### ISSUE TITLE
Re-Design Google Translate

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#257]
Based off this design, please redesign the google translate dropdown.

![image](https://user-images.githubusercontent.com/21111803/41050219-96db3732-6967-11e8-8376-c4e88bd56860.png)

@mnoster you've been shared to the inspect version of this via your metax email.

**Comment by samkim28** [comment]
Updated design and positioning of the google translate element. also moved it into mainsidebar.js to assist with the positioning
