### ISSUE TITLE
HISTORY (Single-Domain Tab)

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#265]
# To Do
- [x] Create a 3 column table that displays the domain's interaction with the registry: (Event, Date, View)
- [x] The interactions are numbered in chronological order

**Events are:**
- [x] Applied (link out to tx on Etherscan)
- [x] Challenged (link out to tx on Etherscan)
- [ ] Accepted (show voting outcome in modal)
- [ ] Rejected (show voting outcome in modal)

**Date**
- If date can be set to whatever time zone the user is, that would be best
- We can always just show the UTC time snapshot from Etherscan

# Resources
[INVISION WIREFRAMES HERE](https://invis.io/DYLWB3TP96W#/302742778_HISTORY)
![image](https://user-images.githubusercontent.com/21111803/41938338-a85b1438-7947-11e8-8c7a-6642b0ae7148.png)

**Comment by mnoster** [comment]
The accepted/rejected outcomes will take a bit longer. To implement.
