### ISSUE TITLE
User should be able to add discussion comments that have line breaks

### ISSUE THREAD

**Issue by stellarmagnet** [AdChain/AdChainRegistryDapp#275]
Right now when you hit enter, it sends your comments. This should be disabled. Allow user to use "Enter" key for like breaks and use a "Submit" button instead to send the comments. (Alternatively, have a checkbox if the user prefers to hit Enter to submit.)

**Comment by waymobetta** [comment]
Hi @stellarmagnet , our comment box already has this functionality. If you hold the `Shift` button while pressing `Enter` it will add a line break.

And thank you for the suggestion about the checkbox. I'll speak with the team about implementing such a feature.

**Comment by stellarmagnet** [comment]
Okay since you are gonna resolve this may I also suggest changing the field type to a "textarea" to support resizing the field/multi-line input.

Right now the UX is more like chat UX, but I think that more of a forum-like UX needs to be implemented since I don't imagine many live synchronous challenge debates.
