### ISSUE TITLE
infura websocket connection is down

### ISSUE THREAD

**Issue by mnoster** [AdChain/AdChainRegistryDapp#78]
Check the console trace for the specific wss:// error being thrown

Most likely infura wss:// endpoint failing

If no solution found, we can maybe switch to http

**Comment by eccheung4** [comment]
Related issue about ws:  https://github.com/INFURA/infura/issues/29

**Comment by Hirama** [comment]
After some time infure drop connection
` _Event {
  type: 'close',
  isTrusted: false,
  _yaeti: true,
  code: 1006,
  reason: 'Connection dropped by remote peer.',
  wasClean: false,
  target: 
   W3CWebSocket {
     _listeners: {},
     addEventListener: [Function: _addEventListener],
     removeEventListener: [Function: _removeEventListener],
     dispatchEvent: [Function: _dispatchEvent],
     _url: 'wss://mainnet.infura.io/ws',
     _readyState: 3,
     _protocol: undefined,
     _extensions: [],
     _bufferedAmount: 0,
     _binaryType: 'arraybuffer',
     _connection: 
      WebSocketConnection {
        _debug: [Function],
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        _pingListenerCount: 0,
        config: [Object],
        socket: [TLSSocket],
        protocol: undefined,
        extensions: [],
        remoteAddress: '52.7.229.46',
        closeReasonCode: 1006,
        closeDescription: 'Connection dropped by remote peer.',
        closeEventEmitted: true,
        maskOutgoingPackets: true,
        maskBytes: <Buffer 71 e2 50 35>,
        frameHeader: <Buffer 81 7e 02 d2 00 00 00 00 00 00>,
        bufferList: [BufferList],
        currentFrame: [WebSocketFrame],
        fragmentationSize: 0,
        frameQueue: [],
        connected: false,
        state: 'closed',
        waitingForCloseResponse: false,
        receivedEnd: true,
        closeTimeout: 5000,
        assembleFragments: true,
        maxReceivedMessageSize: 8388608,
        outputBufferFull: false,
        inputPaused: false,
        receivedDataHandler: [Function: bound ],
        _closeTimerHandler: [Function: bound ],
        webSocketVersion: 13,
        socketHadError: false },
     _client: 
      WebSocketClient {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        config: [Object],
        _req: null,
        protocols: [],
        origin: undefined,
        url: [Url],
        secure: true,
        base64nonce: 'aizaDw8uHb9ey76MkBU7Mw==',
        socket: [TLSSocket],
        response: [IncomingMessage],
        firstDataChunk: null },
     onerror: [Function],
     onclose: [Function],
     onmessage: [Function] },
  cancelable: true,
  stopImmediatePropagation: [Function] }`

**Comment by eccheung4** [comment]
trying using this endpoint for now: wss://rinkeby.infura.io/_ws

infura is working on pinpointing problem

**Comment by mnoster** [comment]
@eccheung4 Thanks will try it out

**Comment by mnoster** [comment]
@eccheung4 Worked. Good stuff.

**Comment by mnoster** [comment]
Closed https://github.com/AdChain/AdChainRegistryDapp/commit/52f2d09429f080b2a6bc7952aa6050fece515eef
