### ISSUE TITLE
Domains Page (UI)

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#79]
The new UI for the domains page will look as shown below with the following instructions being:

![image](https://user-images.githubusercontent.com/21111803/35174227-77522ea8-fd23-11e7-8a2d-378e926b1e08.png)

You can always find a user-flow here: https://projects.invisionapp.com/share/96FA5TZJD#/screens/272872559

All icons (in SVG) can be found here: https://drive.google.com/open?id=1D1w_jEog2XVDdb1gaoK5a6vwuCsgEFn2

## Navigation Column
- [x] **HOW DOES THIS THING WORK** button is filled-in with orange when hovered-over
- [x] The active tab **DOMAINS** has 100% opacity while the inactive tabs have 50% opacity
- [x] The **APPLY DOMAIN** section has a blue border when inactive, but has the same blue be the fill when active. The **APPLY DOMAIN** green button is also an outline when the section is inactive, but is filled-in green when the section is active.
- [x] The "Powered By" section and logos all have shadows, as well as the adChain logo on-top
- [x] The shadows for everything in the Navigation Column are #0D063E with X-offset of 0, Y-offset of 2, and Blur of 10. 
- [x] **HELP** and **SOCIAL** each have a triangle drop-down that is point down when inactive, and to the right when active. When those two are clicked, the user stays on the same page and thus the | line to the left of each main header should remain the same. When those two are clicked, they populate a drop-down of options that open in a new tab. 

## Header
- [x] The user's current wallet address (as found in an unlocked MetaMask) is displayed, along with its bit icon
- [x] The network status is shown (Ethereum Main Network)
- [x] Time Zone dropdown feature that allows for users to see the domain's "Stage Ends" in the time zone of their choosing
- [x] Based off the user's unlocked MetaMask account, their ETH and ADT balance is displayed. Cap the decimal precision to the 4th decimal place (1.0000)

## Global Registry Usage
- [x] Same utility as the existing one, just with the new design

## adToken Calculator
- [x] Same utility as the existing one, just with the new design

## Domain Filters
- [x] Same utility as the existing one, just with the new design

## Global Comment Box
- [x] Same utility as the existing one, just with the new design
- [x] Please rename "Global Trollbox" to "Global Comment Box"

## Domains
- [x] Same utility as the existing one, just with the new design.
- [x] Make sure to have the right color action buttons (vote=blue, challenge=red, reveal=green)
- [x] Make sure to include the hover rectangle and make the entire line clickable. The destination when the user clicks the line is the domain's profile.

### Colors
- Red: #CE3434
- Blue: #3434CE
- Green: #10C903
- Orange: #CE4034

**Comment by mnoster** [comment]
@eduardo-munoz  
Awesome work
