### ISSUE TITLE
My Dashboard Page (UI)

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#81]
The "My Dashboard" page UI will be as seen below and will contain as follows:

All icons (in SVG) can be found here: https://drive.google.com/open?id=1D1w_jEog2XVDdb1gaoK5a6vwuCsgEFn2

You can always find a user-flow here: https://projects.invisionapp.com/share/96FA5TZJD#/screens/272872559

![image](https://user-images.githubusercontent.com/21111803/35300454-4942b574-003d-11e8-8619-476a76e98a49.png)

## Navigation Column
Please reference https://github.com/AdChain/AdChainRegistryDapp/issues/79 for the same Navigation column guidelines.

## Your Summary Row
- [x] Total Domains You Challenged & Tooltip
- [x] Total Times You Committed & Tooltip
- [x] Total Times You Revealed & Tooltip
- [x] Total adToken You Claimed & Tooltip

## ADT Row
- [x] Pre-Approve ADT Transfer & Tooltip
- [x] Request Voting Rights & Tooltip
- [x] Withdraw Voting Rights & Tooltip

## Domains You Applied
- [x] Display all domains applied by the wallet address and their status
- [x] Add the hover over light blue (#F5F5F9) background, similar to the Domains box
- [x] Make the column collapse-able

## Domains You Challenged
- [x] Display all domains challenged by the wallet address and their status
- [x] Add the hover over light blue (#F5F5F9) background, similar to the Domains box
- [x] Make the column collapse-able

## Your Commits to Reveal
- [x] Display all commits that need to be revealed by the wallet address and their status. Sort the domains by earliest Stage Ends time, meaning that the reveals which will finish first will be on-top. Only show domains that have been previously committed and are ACTIVELY in the revealStageLength period.
- [x] Add the hover over light blue (#F5F5F9) background, similar to the Domains box
- [x] Make the column collapse-able

## Claim Rewards
- [x] Since the wallet address has revealed their secret phrase when revealing their vote, we are able to store when a wallet address has ADT to claim. Display which domain has a reward for them, the ADT amount, and the ability to claim the reward straight from the dashboard page. 
- [x] Add the hover over light blue (#F5F5F9) background, similar to the Domains box
- [x] Make the column collapse-able

**Comment by samkim28** [comment]
Need to add tooltips and make columns collapse-able. Rest of the dashboard functionality should be good to go.
