### ISSUE TITLE
Governance Module Page (UI)

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#82]
The "Governance Module" page UI will be as seen below and will contain as follows:

All icons (in SVG) can be found here: https://drive.google.com/open?id=1D1w_jEog2XVDdb1gaoK5a6vwuCsgEFn2

You can always find up-to-date user flows here: https://projects.invisionapp.com/share/96FA5TZJD#/screens/272872559

![image](https://user-images.githubusercontent.com/21111803/35301382-3f12069c-0040-11e8-8888-03d4ac7d20e3.png)

## Navigation Column
Please reference https://github.com/AdChain/AdChainRegistryDapp/issues/79 for the same Navigation column guidelines.

## Core Parameters
- [x] Include the Core Parameter tooltip.
- [x] All Core Parameters are in blue (#3434CE)
- [x] minDeposit with Tooltip and value
- [x] applyStageLength with Tooltip and value
- [x] commitStageLength with Tooltip and value
- [x] revealStageLength with Tooltip and value
- [x] dispensationPct with Tooltip and value
- [x] voteQuorum with Tooltip and value

## Governance Parameters
- [x] Include the Governance Parameter tooltip.
- [x] All Core Parameters are in red (#CE3434)
- [x] gMinDeposit with Tooltip and value
- [x] gApplyStageLength with Tooltip and value
- [x] gCommitStageLength with Tooltip and value
- [x] gRevealStageLength with Tooltip and value
- [x] gDispensationPct with Tooltip and value
- [x] gVoteQuorum with Tooltip and value

## Create Proposal
- [x] Include the Create Proposal Tooltip
- [x] The "Select Parameter" dropdown displays all 12 parameters (in their correct color of red/blue)
- [x] Have the "Enter Proposed Value" field grayed-out until the "Select Parameter" is chosen. Once the "Select Parameter" is filled, have the correct input field for "Enter Proposed Value". Parameters that deal with ADT amounts (minDeposit, gMinDeposit) must have "ADT" at the end of the field and have commas automatically displayed when an amount greater than 999 is entered. Parameters that deal with time (applyStageLength, gApplyStageLength, commitStageLength, etc.) will prompt the user to enter the Days, Hours, and Minutes proposed. Parameters that deal with percentages will have a % symbol automatically populated so that the user knows they're entering a percentage, and not having to enter 0.80 for 80%. 
- [x] The "ADT to Stake" field will have the minimum automatically updated based off the value of gMinDeposit

## Open Proposals
- [x] All Open Proposals are to be displayed in this box (subject to the filter)
- [x] When the user chooses to interact with the proposed parameter value, a modal will pop-up that allows the user to challenge, commit, and reveal votes (based on the stage the proposal is in)

**Comment by mnoster** [comment]
@eduardo-munoz ^^

**Comment by samkim28** [comment]
@mnoster Yup, I'll get it set up
